### ISSUE TITLE
3.1.2

### ISSUE THREAD

**Issue by MoBosse** [SdgTestEnvironment/sdg-data#1]
Prüfung durch DT

**Comment by SDGlauraschroeder** [comment]
Bitte zuerst Prüfung durch mich - wenn wirklich alles fix und schön ist, dann würde ich es gerne erst an DT weitergeben.

**Comment by MoBosse** [comment]
@SDGlauraschroeder Ist auf der Prüfseite aktualisiert.

**Comment by SDGlauraschroeder** [comment]
Hatte immer noch den falschen Key in der Datenbank. Ist jetzt endgültig fertig und kann
@Taubmann-D

**Comment by Taubmann-D** [comment]
Hallo Laura,

ich bin verwirrt, da ich die angegebenen GitHub-Adressen nicht kenne:

- SdgTestEnvironment/sdg-data <reply@reply.github.com>
- SdgTestEnvironment/sdg-data <sdg-data@noreply.github.com>
- Mention <mention@noreply.github.com>

Dennoch gehe ich auf "alle antworten", besser ist besser...

Auf der angegebenen Staging-Seite ist immer noch der falsche Zeitreihentitel. Damit Du Deine Aufgaben diese Woche in Ruhe beenden kannst, übergib die Zeitreihe bitte Svenja.

Vielen Dank und viele Grüße
Doreen



-----Ursprüngliche Nachricht-----
Von: Schroeder-L <notifications@github.com> 
Gesendet: Montag, 30. November 2020 10:58
An: SdgTestEnvironment/sdg-data <sdg-data@noreply.github.com>
Cc: Taubmann, Doreen (G205) <Doreen.Taubmann@destatis.de>; Mention <mention@noreply.github.com>
Betreff: [EXTERN]Re: [SdgTestEnvironment/sdg-data] 3.1.2 (#1)

Hatte immer noch den falschen Key in der Datenbank. Ist jetzt endgültig fertig und kann
@Taubmann-D <https://github.com/Taubmann-D>

**Comment by Taubmann-D** [comment]
@MoBosse; @Linder-S: Bitte auf die Live-Seite hochladen. Danke!
