### ISSUE TITLE
Indikator: 12.4.1

### ISSUE THREAD

**Issue by SDGlauraschroeder** [SdgTestEnvironment/sdg-data#3]
Der im Titel genannte Indikator muss von untenstehender Person auf [dieser Seite](https://sdgtestenvironment.github.io/sdg-indicators/) geprüft werden.

Prüfer: @SDGlauraschroeder

**Comment by MoBosse** [comment]
@SDGlauraschroeder: Ist auf Prüf-Seite aktualisiert.

**Comment by SDGlauraschroeder** [comment]
Hei, Datenquellen wieder vereinheitlicht. Alle haben eine Orga und den gleichen Text. Kann ganz normal hochgeladen werden.
