### ISSUE TITLE
Indikator: 5.5.2 und 8.5.1

### ISSUE THREAD

**Issue by Linder-S** [SdgTestEnvironment/sdg-data#9]
Der im Titel genannte Indikator muss von untenstehender Person auf [dieser Seite](https://sdgtestenvironment.github.io/sdg-indicators/) geprüft werden.

Prüfer: @Linder-S

@MoBosse: Hierbei handelt es sich um die Indikatoren, die am 8.12 auf die Live-Seite geladen werden sollen.

**Comment by MoBosse** [comment]
@Linder-S: Sollten in ein paar Minuten aktualisiert sein.
